name: AWS Secrets
# Run this workflow every time a new commit pushed to your repository.
on: 
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
jobs:
  fetch_some_secrets:
    runs-on: ubuntu-latest
    permissions: # Must change the job token permissions to use JWT auth
      id-token: write
      contents: read
    name: Fetch some static secrets
    steps:
      - name: Fetch secrets from AKeyless
        id: fetch-secrets
        uses: cmancone/akeyless-action@v1.0.0
        with:
          access-id: p-qchvfq9ofg4z
          # we use a JSON string because Github actions don't support dictionaries as inputs
          producer-for-aws-access: '/AWS - ECR - Describe Assume Role'
          # static-secrets: '{"/path/to/static/secret":"output_name"}'
          #dynamic-secrets: '{"/path/to/dynamic/secret":"another_output_name"}'
          # these are true by default, but left here for reference
          export-secrets-to-outputs: true
          export-secrets-to-environment: true
          
      - name: Display fetched secrets
        run: |
          export akl=`wc -m ${{ secrets.AWS_ACCESS_KEY_ID }}`
          export askl=`wc -m ${{ secrets.AWS_SECRET_ACCESS_KEY }}`
          echo "access_key length: $akl"
          echo " access_secret_key length: $askl"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::980459274626:role/my-github-actions-role-cg
          aws-region: us-east-1

      - name: Login to PROD AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Describe ECR
        run: |
          aws ecr describe-repositories --repository-names cg-test > describe-ecr.json
          cat describe-ecr.json
