name: AWS Secrets
# Run this workflow every time a new commit pushed to your repository.
on: 
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
env:
  AWS_REGION: us-east-1

jobs:
  fetch_some_secrets:
    runs-on: ubuntu-latest
    permissions: # Must change the job token permissions to use JWT auth
      id-token: write
      contents: read
    name: Fetch some static secrets
    steps:
      # - name: Fetch secrets from AKeyless
      #   id: fetch-secrets
      #   uses: cmancone/akeyless-action@v1.0.0
      #   with:
      #     access-id: p-qchvfq9ofg4z
      #     # we use a JSON string because Github actions don't support dictionaries as inputs
      #     producer-for-aws-access: '/AWS - ECR - Describe'
      #     # static-secrets: '{"/path/to/static/secret":"output_name"}'
      #     #dynamic-secrets: '{"/path/to/dynamic/secret":"another_output_name"}'
      #     # these are true by default, but left here for reference
      #     export-secrets-to-outputs: true
      #     export-secrets-to-environment: true

      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     role-to-assume: arn:aws:iam::980459274626:role/my-github-actions-role-cg
      #     aws-region: us-east-1

      # - name: Login to PROD AWS ECR
      #   id: login-ecr
      #   uses: aws-actions/amazon-ecr-login@v1

      - name: Describe ECR
        run: |
          set -x
          curl -o akeyless https://akeyless-cli.s3.us-east-2.amazonaws.com/cli/latest/production/cli-linux-amd64
          chmod +x akeyless
          ./akeyless --init
          ./akeyless auth --access-id=p-qchvfq9ofg4z --access-type=jwt --jwt $ACTIONS_ID_TOKEN_REQUEST_TOKEN --json > auth.json
          echo "Masking Akeyless Auth Token: ::add-mask::$(cat auth.json | jq -r .token)"
          ./akeyless get-dynamic-secret-value -n "/AWS - ECR - Describe" --token $(cat auth.json | jq -r .token) --json > aws.json
          touch aws_config
          tee aws_config << EOF
          [default]
          aws_access_key_id=$(cat aws.json | jq -r .access_key_id)
          aws_secret_access_key=$(cat aws.json | jq -r .secret_access_key)
          EOF
          cat aws_config
          export AWS_CONFIG_FILE=aws_config
          aws sts get-session-token > aws-sess.json
          echo "Access Key ID: $(cat aws-sess.json | jq -r .Credentials.AccessKeyId)"
          echo "Masking Secret Access Key: ::add-mask::$(cat aws-sess.json | jq -r .Credentials.SecretAccessKey)"
          echo "Masking Session Token: ::add-mask::$(cat aws-sess.json | jq -r .Credentials.SessionToken)"
          export AWS_ACCESS_KEY_ID=$(cat aws-sess.json | jq -r .Credentials.AccessKeyId)
          export AWS_SECRET_ACCESS_KEY=$(cat aws-sess.json | jq -r .Credentials.SecretAccessKey)
          export AWS_SESSION_TOKEN=$(cat aws-sess.json | jq -r .Credentials.SessionToken)
          aws ecr describe-repositories --repository-names cg-test --region us-east-1 > describe-ecr.json
          cat describe-ecr.json
